// Command gentsconst renders the Go-side single-source-of-truth constants
// (config defaults, validation bounds, UI thresholds) into a TypeScript
// module the frontend can import. Wired via //go:generate in
// internal/config/export.go and the `task gen` target.
//
// The output is committed to the repo. CI / pre-push enforces drift via
// `git diff --exit-code` after running `task gen`.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"text/template"

	"github.com/meopedevts/revu/internal/config"
	"github.com/meopedevts/revu/internal/uilimits"
)

const tsTemplate = `// Code generated by cmd/gentsconst. DO NOT EDIT.
//
// Source of truth lives in:
//   - internal/config (Defaults, Limits)
//   - internal/uilimits (DetailsDiffLimit, PollSafetyIntervalMS)
//
// Regenerate with: task gen
/* eslint-disable */

export const DEFAULT_CONFIG = {
  polling_interval_seconds: {{.Defaults.PollingIntervalSeconds}},
  notifications_enabled: {{.Defaults.NotificationsEnabled}},
  notification_timeout_seconds: {{.Defaults.NotificationTimeoutSeconds}},
  status_refresh_every_n_ticks: {{.Defaults.StatusRefreshEveryNTicks}},
  history_retention_days: {{.Defaults.HistoryRetentionDays}},
  start_hidden: {{.Defaults.StartHidden}},
  window: {
    width: {{.Defaults.Window.Width}},
    height: {{.Defaults.Window.Height}},
  },
  theme: "{{.Defaults.Theme}}",
} as const

export const CONFIG_BOUNDS = {
  pollingIntervalSeconds: { min: {{.Bounds.PollingIntervalSeconds.Min}}, max: {{.Bounds.PollingIntervalSeconds.Max}} },
  notificationTimeoutSeconds: { min: {{.Bounds.NotificationTimeoutSeconds.Min}}, max: {{.Bounds.NotificationTimeoutSeconds.Max}} },
  statusRefreshEveryNTicks: { min: {{.Bounds.StatusRefreshEveryNTicks.Min}}, max: {{.Bounds.StatusRefreshEveryNTicks.Max}} },
  historyRetentionDays: { min: {{.Bounds.HistoryRetentionDays.Min}}, max: {{.Bounds.HistoryRetentionDays.Max}} },
  windowWidth: { min: {{.Bounds.WindowWidth.Min}}, max: {{.Bounds.WindowWidth.Max}} },
  windowHeight: { min: {{.Bounds.WindowHeight.Min}}, max: {{.Bounds.WindowHeight.Max}} },
} as const

export const VALID_THEMES = [{{range $i, $t := .Bounds.ValidThemes}}{{if $i}}, {{end}}"{{$t}}"{{end}}] as const
export type Theme = (typeof VALID_THEMES)[number]

export const DETAILS_DIFF_LIMIT = {{.DetailsDiffLimit}}
export const POLL_SAFETY_INTERVAL_MS = {{.PollSafetyIntervalMS}}
`

type tplData struct {
	Defaults             config.Config
	Bounds               config.Bounds
	DetailsDiffLimit     int
	PollSafetyIntervalMS int
}

func main() {
	root, err := repoRoot()
	if err != nil {
		dief("locate repo root: %v", err)
	}
	out := filepath.Join(root, "frontend", "src", "shared", "generated", "constants.ts")

	tpl, err := template.New("ts").Parse(tsTemplate)
	if err != nil {
		dief("parse template: %v", err)
	}

	data := tplData{
		Defaults:             config.Defaults(),
		Bounds:               config.Limits(),
		DetailsDiffLimit:     uilimits.DetailsDiffLimit,
		PollSafetyIntervalMS: uilimits.PollSafetyIntervalMS,
	}

	var buf bytes.Buffer
	if err := tpl.Execute(&buf, data); err != nil {
		dief("execute template: %v", err)
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o750); err != nil {
		dief("mkdir output dir: %v", err)
	}

	tmp := out + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0o600); err != nil {
		dief("write tmp: %v", err)
	}
	if err := os.Rename(tmp, out); err != nil {
		_ = os.Remove(tmp)
		dief("rename tmp: %v", err)
	}
	fmt.Printf("wrote %s\n", out)
}

// repoRoot walks up from this source file's location until it finds go.mod.
// Resolved at runtime so the generator works regardless of CWD when invoked
// by `go generate`.
func repoRoot() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", errors.New("runtime.Caller failed")
	}
	dir := filepath.Dir(file)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s", file)
		}
		dir = parent
	}
}

func dief(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gentsconst: "+format+"\n", args...)
	os.Exit(1)
}
