/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSectionRouteImport } from './routes/settings/$section'
import { Route as PrPrIdRouteImport } from './routes/pr/$prId'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PrPrIdRoute = PrPrIdRouteImport.update({
  id: '/pr/$prId',
  path: '/pr/$prId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/pr/$prId': typeof PrPrIdRoute
  '/settings/$section': typeof SettingsSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/pr/$prId': typeof PrPrIdRoute
  '/settings/$section': typeof SettingsSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/pr/$prId': typeof PrPrIdRoute
  '/settings/$section': typeof SettingsSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/pr/$prId' | '/settings/$section'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/pr/$prId' | '/settings/$section'
  id: '__root__' | '/' | '/settings' | '/pr/$prId' | '/settings/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  PrPrIdRoute: typeof PrPrIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/pr/$prId': {
      id: '/pr/$prId'
      path: '/pr/$prId'
      fullPath: '/pr/$prId'
      preLoaderRoute: typeof PrPrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  PrPrIdRoute: PrPrIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
